version: '3.4'

networks:
  cors_dev:
    external: true

services:
  db:
    image: mariadb:10.5
    container_name: coreshop-3-mariadb
    networks:
      - cors_dev
    working_dir: /application
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_general_ci]
    volumes:
      - coreshop-3-database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ROOT
      - MYSQL_DATABASE=pimcore
      - MYSQL_USER=pimcore
      - MYSQL_PASSWORD=pimcore
    ports:
      - "3306:3306"

  php:
    build: .
    container_name: coreshop-3-php
    volumes:
      - .:/var/www/html:cached
      - ./.docker/php.ini:/usr/local/etc/php/conf.d/01-custom.ini
    networks:
      - cors_dev
    labels:
      - traefik.enable=true
      - traefik.http.routers.coreshop_3.rule=Host(`coreshop-3.localhost`)
      - traefik.http.routers.coreshop_3.entrypoints=cors_dev
      - traefik.http.routers.coreshop_3.tls=true
      - traefik.http.services.coreshop_3.loadbalancer.server.port=80
      - traefik.docker.network=cors_dev
    depends_on:
     - db

  php-debug:
    image: pimcore/pimcore:PHP8.0-apache-debug
    container_name: coreshop-3-debug-php
    volumes:
      - .:/var/www/html:cached
    networks:
      - cors_dev
    labels:
      - traefik.enable=true
      - traefik.http.routers.coreshop_3_debug.rule=Host(`coreshop-3.localhost`)
      - traefik.http.routers.coreshop_3_debug.tls=true
      - traefik.http.routers.coreshop_3_debug.entrypoints=cors_dev_debug
      - traefik.http.services.coreshop_3_debug.loadbalancer.server.port=80
      - traefik.docker.network=cors_dev
    depends_on:
      - db
    environment:
      - PHP_DEBUG=1
      - PHP_IDE_CONFIG="serverName=localhost"

volumes:
  coreshop-3-database:
